title: A practice of Github
theme: minima
author: Soh Mei Ling
email: meigemini.91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This serves as a purpose of documentation for my R and psychoPy journey

# social links
twitter_username: sohmeiling # DO NOT include the @ character, or else the build will fail!
github_username:  sohmeiling # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
